---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-a
  namespace: development
  name: microservice-a
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: microservice-a