apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger 
  namespace: istio-system
spec:
  hosts:
  - "jaeger.demo"
  gateways:
  - demo-gateway.development.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: jaeger-query.istio-system.svc.cluster.local
        port:
          number: 16686
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: jaeger
  namespace: istio-system
spec:
  host: jaeger-query.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE