apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali 
  namespace: istio-system
spec:
  hosts:
  - "kiali.demo"
  gateways:
  - demo-gateway.development.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali
  namespace: istio-system
spec:
  host: kiali.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE