apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus 
  namespace: istio-system
spec:
  hosts:
  - "prometheus.demo"
  gateways:
  - demo-gateway.development.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: prometheus
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: istio-system
spec:
  host: prometheus.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---