# Source: microservice/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: microservice-a-v3
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-a
        release: microservice-a
        version: v3
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: microservice
          image: "castlemilk/microservice-a:v3"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: management
            timeoutSeconds: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: management
            timeoutSeconds: 3
            initialDelaySeconds: 20
          resources:
            {}
