apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp 
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp 
        release: webapp 
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: webapp
          image: demo
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000 
          livenessProbe:
            httpGet:
              path: / 
              port: 3000 
            timeoutSeconds: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000 
            timeoutSeconds: 3
            initialDelaySeconds: 20
---
