---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp 
  namespace: development
  name: webapp 
spec:
  type: ClusterIP
  ports:
    - port: 3000 
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webapp 